// Generated by scripts/generate-sections.mjs — do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("opiniao")}
      searchBarPlaceholder="Search Opinião…"
      errorToastTitle="Unable to load Opinião"
      emptyTitle="No Opinião articles right now"
      emptyDescription="Check back soon — Opinião stories from Público will appear here."
    />
  );
}
