// Generated by scripts/generate-sections.mjs — do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("brasil")}
      searchBarPlaceholder="Search Brasil…"
      errorToastTitle="Unable to load Brasil"
      emptyTitle="No Brasil articles right now"
      emptyDescription="Check back soon — Brasil stories from Público will appear here."
    />
  );
}
