// Generated by scripts/generate-sections.mjs. Do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={(size) => fetchSection("cultura", size)}
      searchBarPlaceholder="Search Culture…"
      errorToastTitle="Unable to load Culture"
      emptyTitle="No Culture articles right now"
      emptyDescription="Check back soon. Culture articles from Público will appear here."
    />
  );
}
