// Generated by scripts/generate-sections.mjs. Do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={(size) => fetchSection("fotogaleria", size)}
      searchBarPlaceholder="Search Photo Gallery…"
      errorToastTitle="Unable to load Photo Gallery"
      emptyTitle="No Photo Gallery articles right now"
      emptyDescription="Check back soon. Photo Gallery articles from Público will appear here."
    />
  );
}
