// Generated by scripts/generate-sections.mjs — do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("local")}
      searchBarPlaceholder="Search Local…"
      errorToastTitle="Unable to load Local"
      emptyTitle="No Local articles right now"
      emptyDescription="Check back soon — Local stories from Público will appear here."
    />
  );
}
