// Generated by scripts/generate-sections.mjs — do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("casa")}
      searchBarPlaceholder="Search Casa…"
      errorToastTitle="Unable to load Casa"
      emptyTitle="No Casa articles right now"
      emptyDescription="Check back soon — Casa stories from Público will appear here."
    />
  );
}
