// Generated by scripts/generate-sections.mjs — do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("politica")}
      searchBarPlaceholder="Search Política…"
      errorToastTitle="Unable to load Política"
      emptyTitle="No Política articles right now"
      emptyDescription="Check back soon — Política stories from Público will appear here."
    />
  );
}
