// Generated by scripts/generate-sections.mjs — do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("lisboa")}
      searchBarPlaceholder="Search Lisboa…"
      errorToastTitle="Unable to load Lisboa"
      emptyTitle="No Lisboa articles right now"
      emptyDescription="Check back soon — Lisboa stories from Público will appear here."
    />
  );
}
