// Generated by scripts/generate-sections.mjs — do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("gente")}
      searchBarPlaceholder="Search Gente…"
      errorToastTitle="Unable to load Gente"
      emptyTitle="No Gente articles right now"
      emptyDescription="Check back soon — Gente stories from Público will appear here."
    />
  );
}
