// Generated by scripts/generate-sections.mjs — do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("fotogaleria")}
      searchBarPlaceholder="Search Fotogaleria…"
      errorToastTitle="Unable to load Fotogaleria"
      emptyTitle="No Fotogaleria articles right now"
      emptyDescription="Check back soon — Fotogaleria stories from Público will appear here."
    />
  );
}
