// Generated by scripts/generate-sections.mjs. Do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={(size) => fetchSection("p3", size)}
      searchBarPlaceholder="Search P3…"
      errorToastTitle="Unable to load P3"
      emptyTitle="No P3 articles right now"
      emptyDescription="Check back soon. P3 articles from Público will appear here."
    />
  );
}
