// Generated by scripts/generate-sections.mjs — do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("parlamento")}
      searchBarPlaceholder="Search Parlamento…"
      errorToastTitle="Unable to load Parlamento"
      emptyTitle="No Parlamento articles right now"
      emptyDescription="Check back soon — Parlamento stories from Público will appear here."
    />
  );
}
