// Generated by scripts/generate-sections.mjs — do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("viagens")}
      searchBarPlaceholder="Search Viagens…"
      errorToastTitle="Unable to load Viagens"
      emptyTitle="No Viagens articles right now"
      emptyDescription="Check back soon — Viagens stories from Público will appear here."
    />
  );
}
