// Generated by scripts/generate-sections.mjs — do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("europa")}
      searchBarPlaceholder="Search Europa…"
      errorToastTitle="Unable to load Europa"
      emptyTitle="No Europa articles right now"
      emptyDescription="Check back soon — Europa stories from Público will appear here."
    />
  );
}
