// Generated by scripts/generate-sections.mjs — do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("desporto")}
      searchBarPlaceholder="Search Desporto…"
      errorToastTitle="Unable to load Desporto"
      emptyTitle="No Desporto articles right now"
      emptyDescription="Check back soon — Desporto stories from Público will appear here."
    />
  );
}
