// Generated by scripts/generate-sections.mjs — do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("multimedia")}
      searchBarPlaceholder="Search Multimédia…"
      errorToastTitle="Unable to load Multimédia"
      emptyTitle="No Multimédia articles right now"
      emptyDescription="Check back soon — Multimédia stories from Público will appear here."
    />
  );
}
