// Generated by scripts/generate-sections.mjs — do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("porto")}
      searchBarPlaceholder="Search Porto…"
      errorToastTitle="Unable to load Porto"
      emptyTitle="No Porto articles right now"
      emptyDescription="Check back soon — Porto stories from Público will appear here."
    />
  );
}
