// Generated by scripts/generate-sections.mjs. Do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={(size) => fetchSection("politica", size)}
      searchBarPlaceholder="Search Politics…"
      errorToastTitle="Unable to load Politics"
      emptyTitle="No Politics articles right now"
      emptyDescription="Check back soon. Politics articles from Público will appear here."
    />
  );
}
