// Generated by scripts/generate-sections.mjs — do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("sociedade")}
      searchBarPlaceholder="Search Sociedade…"
      errorToastTitle="Unable to load Sociedade"
      emptyTitle="No Sociedade articles right now"
      emptyDescription="Check back soon — Sociedade stories from Público will appear here."
    />
  );
}
