// Generated by scripts/generate-sections.mjs — do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("automoveis")}
      searchBarPlaceholder="Search Automóveis…"
      errorToastTitle="Unable to load Automóveis"
      emptyTitle="No Automóveis articles right now"
      emptyDescription="Check back soon — Automóveis stories from Público will appear here."
    />
  );
}
