// Generated by scripts/generate-sections.mjs — do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("tecnologia")}
      searchBarPlaceholder="Search Tecnologia…"
      errorToastTitle="Unable to load Tecnologia"
      emptyTitle="No Tecnologia articles right now"
      emptyDescription="Check back soon — Tecnologia stories from Público will appear here."
    />
  );
}
