// Generated by scripts/generate-sections.mjs — do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("ciencia")}
      searchBarPlaceholder="Search Ciência…"
      errorToastTitle="Unable to load Ciência"
      emptyTitle="No Ciência articles right now"
      emptyDescription="Check back soon — Ciência stories from Público will appear here."
    />
  );
}
