// Generated by scripts/generate-sections.mjs — do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("mundo")}
      searchBarPlaceholder="Search Mundo…"
      errorToastTitle="Unable to load Mundo"
      emptyTitle="No Mundo articles right now"
      emptyDescription="Check back soon — Mundo stories from Público will appear here."
    />
  );
}
