// Generated by scripts/generate-sections.mjs. Do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={(size) => fetchSection("economia", size)}
      searchBarPlaceholder="Search Economy…"
      errorToastTitle="Unable to load Economy"
      emptyTitle="No Economy articles right now"
      emptyDescription="Check back soon. Economy articles from Público will appear here."
    />
  );
}
