// Generated by scripts/generate-sections.mjs — do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("videos")}
      searchBarPlaceholder="Search Vídeos…"
      errorToastTitle="Unable to load Vídeos"
      emptyTitle="No Vídeos articles right now"
      emptyDescription="Check back soon — Vídeos stories from Público will appear here."
    />
  );
}
